# Generated by Django 5.2.6 on 2025-09-09 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('texto_email', models.TextField()),
                ('arquivo_email', models.FileField(blank=True, null=True, upload_to='emails/')),
                ('resposta_email', models.TextField(blank=True, null=True)),
                ('tipo_classificacao', models.TextField(blank=True, null=True)),
                ('classificacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
